// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jpillora/overseer"
	"github.com/xuender/weigh/proxy"
)

// Injectors from wire.go:

func InitCfg(env *Env) *overseer.Config {
	config := NewConfig(env)
	limits := proxy.NewLimits()
	service := proxy.NewService(config, limits)
	handler := proxy.NewHandler(service)
	overseerConfig := NewOverseerCfg(env, handler)
	return overseerConfig
}
